services:
  - type: web
    name: ly-watchdog-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    plan: free
    region: oregon
    healthCheckPath: /health
    dockerPort: 8000
    envVars:
      - key: DATABASE_URL
        sync: false
